---
title: "Analysis"
author: "Alicia Canales"
date: "2023-05-04"
output: 
  html_document:
    code_folding: 'hide'
---

```{r setup, include=FALSE, message=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE, results=FALSE, message=FALSE)
# removed "include" to plot figues on the Markdown
```

```{r}
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(tsibble)
library(lubridate)
library(feasts)
library(patchwork)
library(kableExtra)
library(purrr)
```

### Importing data **this is only the first page of the excel sheet**
```{r}
#your mom

coho <- readxl::read_xlsx(here('data', 'OC Coho Abundance.xlsx')) %>% #,skip = 1, col_names = TRUE) %>%
  clean_names() %>% 
  distinct()

coho_1 <- readxl::read_xlsx(here('data', 'wil_coho_harvest_estimates.xlsx')) %>%
  clean_names()

coho_2 <- readxl::read_xlsx(here('data', 'wild_spawner_abundance.xlsx')) %>%
  clean_names()


## changing the names of the columns
#colnames(coho) <- coho[1,] #Removed first column of data set so don't think this for now (I think - Olivia)

## making things more tidy
clean_coho <- coho[-1,] %>% 
  clean_names() %>% 
  pivot_longer('alsea':'yaquina',
               names_to = 'name',
               values_to = 'count')

## readxl is a package but since we only need one function from it we don't have to call the whole thing from our library. In the future, if we see a package that we only need one function from we can call it within a code chunk with '::' and the desired function following.
```


```{r}
# plot 21 time series. 4 x 5 panels. This would be for trends
# calculate returns --> we the need to plot this and see if there is an absensce of trend or not
# x axis is time y axis is return calculation
# mean over time 

# verify that there are duplicates
# variance of Returns
# calculate covariance --> there should just be a function for this. maybe find a way to put the whole matrix in the function


```


## Create figures of each population from 1994-2019
```{r}
coho_yr <- coho %>%
  mutate(date = lubridate::mdy(year)) #Convert to date for tibble

coho_ts <- coho_yr %>%
 as_tsibble(key = NULL, index = year) #Convert to tibble for timeseries

pop_alsea <- ggplot(data = coho_ts, aes(x = year, y = alsea)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Alsea") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_beaver <- ggplot(data = coho_ts, aes(x = year, y = beaver)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Beaver") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_coos <- ggplot(data = coho_ts, aes(x = year, y = coos)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Coos") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_coquille <- ggplot(data = coho_ts, aes(x = year, y = coquille)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Coquille") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_floras <- ggplot(data = coho_ts, aes(x = year, y = floras)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Floras") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_lower_umpqua <- ggplot(data = coho_ts, aes(x = year, y = lower_umpqua)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Lower Umpqua") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_middle_umpqua <- ggplot(data = coho_ts, aes(x = year, y = middle_umpqua)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Middle Umpqua") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_necanicum <- ggplot(data = coho_ts, aes(x = year, y = necanicum)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Necanicum") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_nehalem <- ggplot(data = coho_ts, aes(x = year, y = nehalem)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Mehalem") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_nestucca <- ggplot(data = coho_ts, aes(x = year, y = nestucca)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Nestucca") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_north_umpqua <- ggplot(data = coho_ts, aes(x = year, y = north_umpqua)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "North Umpqua") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_salmon <- ggplot(data = coho_ts, aes(x = year, y = salmon)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Salmon") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_siletz <- ggplot(data = coho_ts, aes(x = year, y = siletz)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Siletz") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_siltcoos <- ggplot(data = coho_ts, aes(x = year, y = siltcoos)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Siltcoos") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_siuslaw <- ggplot(data = coho_ts, aes(x = year, y = siuslaw)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Siuslaw") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_sixes <- ggplot(data = coho_ts, aes(x = year, y = sixes)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Sixes") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_south_umpqua <- ggplot(data = coho_ts, aes(x = year, y = south_umpqua)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "South Umpqua") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_tahkenitch <- ggplot(data = coho_ts, aes(x = year, y = tahkenitch)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Tahkenitch") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_tenmile <- ggplot(data = coho_ts, aes(x = year, y = tenmile)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Tenmile") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_tillamook <- ggplot(data = coho_ts, aes(x = year, y = tillamook)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Tillamook") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pop_yaquina <- ggplot(data = coho_ts, aes(x = year, y = yaquina)) +
  geom_line(color = "#453781FF") +
  scale_x_continuous(breaks=seq(1994, 2019, by = 1)) +
  labs(x = "Year",
      y = "Population Count",
      title = "Yaquina") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


#pop_alsea
#pop_beaver
#pop_coos
#pop_coquille
#pop_floras
#pop_lower_umpqua
#pop_middle_umpqua
#pop_necanicum
#pop_nehalem
#pop_nestucca
#pop_north_umpqua
#pop_salmon
#pop_siletz
#pop_siltcoos
#pop_siuslaw
#pop_sixes
#pop_south_umpqua
#pop_tahkenitch
#pop_tenmile
#pop_tillamook
#pop_yaquina
```

#Panel of figures of Y(it) - Annual population for each independent population
```{r}
patchwork::plot_layout(pop_alsea + pop_beaver + pop_coos + pop_coquille)

patchwork::plot_layout(pop_floras + pop_lower_umpqua + pop_middle_umpqua + pop_necanicum)

patchwork::plot_layout(pop_nehalem + pop_nestucca + pop_north_umpqua + pop_salmon)

patchwork::plot_layout(pop_siletz + pop_siltcoos + pop_siuslaw + pop_sixes)

patchwork::plot_layout(pop_south_umpqua + pop_tahkenitch + pop_tenmile + pop_tillamook)

patchwork::plot_layout(pop_yaquina)
```


## Calculate sample means of each population
```{r}
#This is more concise in the next code chunk, but I thought I would leave this here in case we don't want to use the sapply function.

sample_means <- colMeans(coho)

kable(sample_means, format = "markdown", digits = 3,caption = "**Sample Means**")
```

## Calculate Mean, Variance, SD, Covariance of each population
```{r}
#Just learned about the sapply function and it is SO COOL. #When I compare these mean/var/sd to those that I manually calculated in excel, they don't match. Can someone check this? Thanks! - Olivia 
## Did you make sure you took out the duplicates in the excel sheet? Cause I only took them out in R. I just checked in excel and they match!!

pop_mean <- sapply(coho, mean)
pop_variance <- sapply(coho, var)
pop_sd <- sapply(coho, sd)
cov(coho)

# data check
mean(coho$alsea)
var(coho$alsea)
sd(coho$alsea)
cov(coho$alsea, coho$beaver)

df1 <- data.frame(pop_mean, pop_variance, pop_sd) #combine data into one data frame

## In case we need to get the variance of a population (instead of a sample):
# var_pop <- function(x) {
#   mean((x-mean(x))^2)
# }

# var_pop(coho$alsea)
```

```{r, results = TRUE}
# Plot table
kable(df1, format = "markdown")
```

# Calculating R(it) -- Returns
```{r}
return <- function(df){
  rt = df$col1[2]/df$col1[1] - 1
  return(rt)
} # essentially this is the equation we want to apply to all of the population years. X0 being count of population at a certain T(time) and X1 being the count of the following year. Correct me if i'm wrong? 


```

